### ISSUE TITLE
suggestion: the callback should have an "err" parameter

### ISSUE THREAD

**Issue by mrose17** [mjhasbach/MOIRA#1]
if an IP address can not be found after exhausting all responses, then the callback should be invoked with an error parameter. if we want to keep the existing signature, then perhaps the callback could be invoked without arguments...

**Comment by mjhasbach** [comment]
Thanks for the feedback! I fixed this in the latest version by adding an error argument to the callback; however, for the next version, I believe I'll make the callback arguments optional and provide convenience methods.

**Comment by mrose17** [comment]
hi. thanks very much for the speedy reply.

just an fyi for the future (not for now): the usual node.js convention is to make the "err" parameter the first parameter, and if that parameter is non-null, then the callback ignores the other parameters, e.g.,

```
     …, function(err, results) {
         if (!!err) return console.log('callback: ' + err.message);

         …
     });
```

i'm not suggesting that you change moira to use that, just that you keep it in mind for the future

**Comment by mjhasbach** [comment]
Thanks for the suggestion. The new code addresses this (null is now returned instead of false) and  is much cleaner. I noticed that MOIRA is a dependency in some of your projects; please be aware that I moved err to the first parameter position in getIP().

**Comment by mrose17** [comment]
got it, thanks!
